build(ci): new CI/CD pipeline capable of building only changed images
1. It can be triggered based on changed files, or manually.
- for PRs it builds all changed images relative to the target branch,
both directly changed images, and changes in the base images.
The dependencies are captured in a separate json file which is
interpreted by a dedicated python script.
- for branch builds it looks at the changes in the last commit.
The logic for dependencies is similar to PRs
- in case of manual parameters the users can build any images
this is useful in case of rebuilds or clean-building everything

2. Needed to make some changes to the makefiles, and split
the .mk files, in order to better track which variables
impact witch image build. Otherwise a change in a config.mk would
trigger all builds.

3. Deleted the folder for the missing/unneeded image busybox.

4. Tweaked the curl installation since it was failing against
newer rockly linux package versions.

5. Refactor building/applying rootfs diffs. This change requires a
stacker version based on a private branch, which allows importing
files straight under the / directory.
- we we have actual reuse of base layers between images instead of a
flat hierarchy
- this was also needed because images depended on build-only layers
defined in stackerfiles of other images, making partial builds
impossible since the build-only dependencies are not available

6. Start publishing the devel layer and add dependencies for cmake.

7. Update the build scripts to pull unchanged dependencies
from the registry used to publish images

8. Temporarily remove squashfs builds, as stacker is throwing an error.

Signed-off-by: Andrei Aaron <aaaron@luxoft.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,31 +1,102 @@
+name: build
+
 on:
   push:
-    paths:
-      - images/**
+    tags:  # Use tags trigger instead of releases, tags are supported by tj-actions/changed-files
+      - 'v*'
     branches:
       - main
+    paths:
+      - images/**
+      - '**.mk'
+      - .github/workflows/ci-cd.yaml
   pull_request:
-    paths:
-      - images/**
-      - config.mk
-      - .github/workflows/build.yaml
     branches:
       - main
-  release:
-    types:
-      - published
-name: build
+    paths:
+      - images/**
+      - '**.mk'
+      - .github/workflows/ci-cd.yaml
+  workflow_dispatch:
+    inputs:
+      folders:
+        description: 'Folders to build'
+        required: true
+        default: ''
 
 permissions: read-all
 
 jobs:
+  generate_build_input:
+    name: "Generate build input"
+    runs-on: ubuntu-latest
+    outputs:
+      folders_to_build: ${{ env.FOLDERS }}
+    steps:
+      - name: Check out source code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Read modified folders from parameters
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        run: |
+          echo "CANDIDATE_FOLDERS=${{ github.event.inputs.folders }}" >> $GITHUB_ENV
+      - name: Read modified files from commit
+        id: changed_files
+        if: ${{ github.event_name != 'workflow_dispatch' }}
+        uses: tj-actions/changed-files@v35
+        with:
+          files: |
+            images/**
+            *.mk
+      - name: Identify modified folders from commit
+        if: ${{ github.event_name != 'workflow_dispatch' }}
+        run: |
+          set -x
+          cd ${GITHUB_WORKSPACE}
+          folders=""
+          for changed_file in ${{ steps.changed_files.outputs.all_modified_files }}; do
+            if [[ "${changed_file}" == *.mk ]]; then
+              # use make magic to identify which makefiles under images include a particular .mk under repo root
+              for folder in $(ls ./images/); do
+                if make -pn -C ./images/${folder} | grep $(basename ${changed_file}); then
+                  folders="${folders} ${folder}"
+                fi
+              done
+            fi
+            folder=$(echo ${changed_file} | awk -F / '{print $2}')
+            folders="${folders} ${folder}"
+          done
+          folders=$(echo ${folders} | tr ' ' '\n' | sort -u | tr '\n' ' ')
+          echo CANDIDATE_FOLDERS="${folders}" >> $GITHUB_ENV
+      - name: Validate folders to build
+        run: |
+          set -x
+          for folder in ${CANDIDATE_FOLDERS}; do
+            [ -f "${GITHUB_WORKSPACE}/images/${folder}/stacker.yaml" ] && [ -f "${GITHUB_WORKSPACE}/images/${folder}/Makefile" ] && folders="${folders} ${folder}" 
+          done
+          folders=$(echo ${folders} | xargs echo -n)
+          if [ -z "${folders}" ]; then
+            echo "No valid folders to build"
+            if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
+              echo "Manually triggered build needs valid folders to build"
+              exit 1
+            else
+              echo "Build will not fail as it is triggered automatically"
+            fi
+          fi
+          echo "FOLDERS=${folders}" >> $GITHUB_ENV
+
   build:
-    if: github.event_name != 'release'
-    name: Build
+    name: Build only
+    needs: [generate_build_input]
+    if: |
+      (!startsWith(github.ref, 'refs/tags/v')) &&
+      (needs.generate_build_input.outputs.folders_to_build != '')
     runs-on: ubuntu-latest
     timeout-minutes: 15
     strategy:
-      max-parallel: 2
+      max-parallel: 3
       matrix:
         os:
           - linux
@@ -35,94 +106,64 @@ jobs:
           - debian-bullseye
           - ubuntu-jammy
           - rockylinux-9
-        image:
-          - static
-          - base
-          - openj9
-          - go-devel
-          - openj9-devel
-          - multitool
     steps:
       - name: Check out source code
         uses: actions/checkout@v3
       - name: Setup env vars
         run: |
-          cat config.mk | sed /^#.*$/d | sed s/\?=/=/g | sed s/#.*$//g | egrep -v "COMMIT|MAKE|DISTRO" > $GITHUB_ENV
           distro=${{ matrix.distro }}
           x=$(echo $distro | tr '-' ' ')
           DISTRO=$(echo $x| awk '{print $1}')
           echo DISTRO=$DISTRO >> $GITHUB_ENV
           DISTRO_REL=$(echo $x| awk '{print $2}')
           echo DISTRO_REL=$DISTRO_REL >> $GITHUB_ENV
-          cat config.mk | sed /^#.*$/d | sed s/\?=/=/g | sed s/#.*$//g | egrep -v "COMMIT|MAKE|DISTRO" > config.vars
-          cat ./config.vars
-          source ./config.vars
-          if [ "${{ matrix.image }}" = "static" ] || [ "${{ matrix.image }}" = "base" ] || [ "${{ matrix.image }}" = "multitool" ]; then
-            TAG=$DISTRO_REL
-          elif [ "${{ matrix.image }}" == "go-devel" ]; then
-            TAG=$GOLANG
-          elif [ "${{ matrix.image }}" == "openj9-devel" ] || [ "${{ matrix.image }}" == "openj9" ]; then
-            TAG=$(echo $OPENJDK | awk -F "." '/1/ {print $1}')
-          else
-            exit 1
-          fi
-          SHA=${{ github.sha }}
-          SHA=${SHA::7}
-          echo SHA=$SHA >> $GITHUB_ENV
-          echo IMAGE=${{ matrix.image }}-${{ matrix.arch }} >> $GITHUB_ENV
-          IMAGE_TAG=$TAG-${SHA}
-          echo IMAGE_TAG=$IMAGE_TAG
-          echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_ENV
-          echo DESCRIPTION="$(cat images/${{ matrix.image }}/README.md)" >> $GITHUB_ENV
-          echo LICENSES="$(cat images/${{ matrix.image }}/LICENSE.md)" >> $GITHUB_ENV
+          echo ARCH=${{ matrix.arch }} >> $GITHUB_ENV
+          echo OS=${{ matrix.os }} >> $GITHUB_ENV
+          echo SUBDIRS="${{needs.generate_build_input.outputs.folders_to_build}}" >> $GITHUB_ENV
+          echo ZOT_VERSION="v2.0.0-rc3" >> $GITHUB_ENV
       - name: Run zot container image with podman
         run: |
-          wget -N https://raw.githubusercontent.com/project-zot/zot/main/examples/config-cve.json
+          wget -N https://raw.githubusercontent.com/project-zot/zot/${ZOT_VERSION}/examples/config-cve.json
           sed -i s/127\.0\.0\.1/0.0.0.0/g config-cve.json
           sed -i s/8080/5000/g config-cve.json
-          podman run -d -p 5000:5000 -v $PWD/config-cve.json:/etc/zot/config.json ghcr.io/project-zot/zot-linux-amd64:latest
+          podman run -d -p 5000:5000 -v $PWD/config-cve.json:/etc/zot/config.json ghcr.io/project-zot/zot-linux-amd64:${ZOT_VERSION}
       - name: Build and push container images
-        uses: project-stacker/stacker-build-push-action@main
-        with:
-          file: images/${{ matrix.image }}/stacker.yaml
-          layer-type: tar squashfs
-          build-args: |
-            REVISION=${{ env.SHA }}
-            DESCRIPTION="${{ env.DESCRIPTION }}"
-            LICENSES="${{ env.LICENSES }}"
-            OS=${{ matrix.os }}
-            ARCH=${{ matrix.arch }}
-            DISTRO=${{ env.DISTRO }}
-            DISTRO_REL=${{ env.DISTRO_REL }}
-            BUSYBOX=${{ env.BUSYBOX }}
-            GOLANG=${{ env.GOLANG }}
-            GOLANG_HASH=${{ env.GOLANG_HASH }}
-            GOLANG_DLV=${{ env.GOLANG_DLV }}
-            GOLANG_LINTER=${{ env.GOLANG_LINTER }}
-            OPENJDK=${{ env.OPENJDK }}
-            OPENJ9=${{ env.OPENJ9 }}
-            OPENJ9_JDK_HASH=${{ env.OPENJ9_JDK_HASH }}
-            OPENJ9_JRE_HASH=${{ env.OPENJ9_JRE_HASH }}
-            SOCAT=${{ env.SOCAT }}
-            LIBNET=${{ env.LIBNET }}
-            ARPING=${{ env.ARPING }}
-            TCPDUMP=${{ env.TCPDUMP }}
-            TRACEROUTE=${{ env.TRACEROUTE }}
-          url: docker://localhost:5000/c3/${{ env.DISTRO }}
-          tags: ${{ env.IMAGE_TAG }}
-          skip-tls: true
+        run: |
+          cd ${GITHUB_WORKSPACE}
+          echo "Building ${SUBDIRS}"
+          make build \
+            SUBDIRS="${SUBDIRS}" \
+            PUBLISH_URL=docker://localhost:5000/c3 \
+            PUBLISH_EXTRA_ARGS="--skip-tls" \
+            PULL_EXTRA_ARGS="--src-tls-verify=false"
+          make publish \
+            SUBDIRS="${SUBDIRS}" \
+            PUBLISH_URL=docker://localhost:5000/c3 \
+            PUBLISH_EXTRA_ARGS="--skip-tls" \
+            PULL_EXTRA_ARGS="--src-tls-verify=false"
       - name: Scan container images
         run: |
+          set -x
+          cd ${GITHUB_WORKSPACE}
           # download zli
-          wget -N https://github.com/project-zot/zot/releases/latest/download/zli-linux-amd64 -O zli
-          chmod +x ./zli
-          ./zli config add local http://localhost:5000
-          ./zli config local verify-tls false
-          ./zli config local showspinner false
-          ./zli cve local -I c3/${{ env.DISTRO }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
-  release:
-    name: Release
-    if: github.event_name == 'release' && github.event.action == 'published'
+          wget -N https://github.com/project-zot/zot/releases/download/${ZOT_VERSION}/zli-linux-amd64 -O hack/tools/bin/zli
+          chmod +x hack/tools/bin/zli
+          hack/tools/bin/zli config add local http://localhost:5000
+          hack/tools/bin/zli config local verify-tls false
+          hack/tools/bin/zli config local showspinner false
+          # there is an assumption that every folder contains a single image defined
+          # in the stacker yaml, having the same name as the folder
+          for folder in ${SUBDIRS}; do
+            tag=$(make -C images/${folder} --no-print-directory tag)
+            hack/tools/bin/zli cve local -I c3/${DISTRO}/${folder}-${ARCH}:${tag}
+          done
+
+  tag:
+    name: Build and publish
+    needs: [generate_build_input]
+    if: |
+      (startsWith(github.ref, 'refs/tags/v')) &&
+      (needs.generate_build_input.outputs.folders_to_build != '')
     runs-on: ubuntu-latest
     timeout-minutes: 15
     env:
@@ -138,84 +179,48 @@ jobs:
           - debian-bullseye
           - ubuntu-jammy
           - rockylinux-9
-        image:
-          - static
-          - base
-          - openj9
-          - go-devel
-          - openj9-devel
-          - multitool
     steps:
       - name: Check out source code
         uses: actions/checkout@v3
       - name: Setup env vars
         run: |
-          cat config.mk | sed /^#.*$/d | sed s/\?=/=/g | sed s/#.*$//g | egrep -v "COMMIT|MAKE|DISTRO" > $GITHUB_ENV
           distro=${{ matrix.distro }}
           x=$(echo $distro | tr '-' ' ')
           DISTRO=$(echo $x| awk '{print $1}')
           echo DISTRO=$DISTRO >> $GITHUB_ENV
           DISTRO_REL=$(echo $x| awk '{print $2}')
           echo DISTRO_REL=$DISTRO_REL >> $GITHUB_ENV
-          cat config.mk | sed /^#.*$/d | sed s/\?=/=/g | sed s/#.*$//g | egrep -v "COMMIT|MAKE|DISTRO" > config.vars
-          cat ./config.vars
-          source ./config.vars
-          if [ "${{ matrix.image }}" = "static" ] || [ "${{ matrix.image }}" = "base" ] || [ "${{ matrix.image }}" = "multitool" ]; then
-            TAG=$DISTRO_REL
-          elif [ "${{ matrix.image }}" == "go-devel" ]; then
-            TAG=$GOLANG
-          elif [ "${{ matrix.image }}" == "openj9-devel" ] || [ "${{ matrix.image }}" == "openj9" ]; then
-            TAG=$(echo $OPENJDK | awk -F "." '/1/ {print $1}')
-          else
-            exit 1
-          fi
-          SHA=${{ github.sha }}
-          SHA=${SHA::7}
-          echo SHA=$SHA >> $GITHUB_ENV
-          echo IMAGE=${{ matrix.image }}-${{ matrix.arch }} >> $GITHUB_ENV
-          IMAGE_TAG=$TAG
-          echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_ENV
-          echo DESCRIPTION="$(cat images/${{ matrix.image }}/README.md)" >> $GITHUB_ENV
-          echo LICENSES="$(cat images/${{ matrix.image }}/LICENSE.md)" >> $GITHUB_ENV
-      - name: Publish container images to zothub.io
-        uses: project-stacker/stacker-build-push-action@main
-        with:
-          file: images/${{ matrix.image }}/stacker.yaml
-          layer-type: tar squashfs
-          build-args: |
-            REVISION=${{ env.SHA }}
-            DESCRIPTION="${{ env.DESCRIPTION }}"
-            LICENSES="${{ env.LICENSES }}"
-            OS=${{ matrix.os }}
-            ARCH=${{ matrix.arch }}
-            DISTRO=${{ env.DISTRO }}
-            DISTRO_REL=${{ env.DISTRO_REL }}
-            BUSYBOX=${{ env.BUSYBOX }}
-            GOLANG=${{ env.GOLANG }}
-            GOLANG_HASH=${{ env.GOLANG_HASH }}
-            GOLANG_DLV=${{ env.GOLANG_DLV }}
-            GOLANG_LINTER=${{ env.GOLANG_LINTER }}
-            OPENJDK=${{ env.OPENJDK }}
-            OPENJ9=${{ env.OPENJ9 }}
-            OPENJ9_JDK_HASH=${{ env.OPENJ9_JDK_HASH }}
-            OPENJ9_JRE_HASH=${{ env.OPENJ9_JRE_HASH }}
-            SOCAT=${{ env.SOCAT }}
-            LIBNET=${{ env.LIBNET }}
-            ARPING=${{ env.ARPING }}
-            TCPDUMP=${{ env.TCPDUMP }}
-            TRACEROUTE=${{ env.TRACEROUTE }}
-          url: docker://zothub.io/c3/${{ env.DISTRO }}
-          tags: ${{ env.IMAGE_TAG }}
-          username: ${{ secrets.ZOTHUB_USERNAME }}
-          password: ${{ secrets.ZOTHUB_PASSWORD }}
+          echo ARCH=${{ matrix.arch }} >> $GITHUB_ENV
+          echo OS=${{ matrix.os }} >> $GITHUB_ENV
+          echo SUBDIRS="${{needs.generate_build_input.outputs.folders_to_build}}" >> $GITHUB_ENV
+          echo ZOT_VERSION="v1.4.3" >> $GITHUB_ENV
+      - name: Build and push container images
+        run: |
+          cd ${GITHUB_WORKSPACE}
+          echo "Building ${SUBDIRS}"
+          make build \
+            SUBDIRS="${SUBDIRS}" \
+            PUBLISH_URL=docker://zothub.io/c3 \
+            PUBLISH_EXTRA_ARGS="--username ${{ secrets.ZOTHUB_USERNAME }} --password ${{ secrets.ZOTHUB_PASSWORD }}"
+          make publish \
+            SUBDIRS="${SUBDIRS}" \
+            PUBLISH_URL=docker://zothub.io/c3 \
+            PUBLISH_EXTRA_ARGS="--username ${{ secrets.ZOTHUB_USERNAME }} --password ${{ secrets.ZOTHUB_PASSWORD }}"
       - name: Scan container images
         run: |
+          set -x
+          cd ${GITHUB_WORKSPACE}
           # download zli
-          wget -N https://github.com/project-zot/zot/releases/latest/download/zli-linux-amd64 -O zli
-          chmod +x ./zli
-          ./zli config add zothub https://zothub.io
-          ./zli config zothub showspinner false
-          ./zli cve zothub -I c3/${{ env.DISTRO }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
+          wget -N https://github.com/project-zot/zot/releases/download/${ZOT_VERSION}/zli-linux-amd64 -O hack/tools/bin/zli
+          chmod +x hack/tools/bin/zli
+          hack/tools/bin/zli config add zothub https://zothub.io
+          hack/tools/bin/zli config zothub showspinner false
+          # there is an assumption that every folder contains a single image defined
+          # in the stacker yaml, having the same name as the folder
+          for folder in ${SUBDIRS}; do
+            tag=$(make -C images/${folder} --no-print-directory tag)
+            hack/tools/bin/zli cve zothub -I c3/${DISTRO}/${folder}-${ARCH}:${tag}
+          done
       - name: Login to zothub.io Registry
         uses: docker/login-action@v2
         with:
@@ -235,15 +240,15 @@ jobs:
         run: cosign version
       - name: Sign image with a key
         run: |
-          cosign sign --key env://COSIGN_PRIVATE_KEY zothub.io/c3/${{ env.DISTRO }}/${{ env.IMAGE }}:${TAGS}
+          # there is an assumption that every folder contains a single image defined
+          # in the stacker yaml, having the same name as the folder
+          for folder in ${SUBDIRS}; do
+            tag=$(make -C images/${folder} --no-print-directory tag)
+            cosign sign --key env://COSIGN_PRIVATE_KEY zothub.io/c3/${DISTRO}/${folder}-${ARCH}:${tag}
+            # Need to retest squashfs builds, getting some errors locally
+            # cosign sign --key env://COSIGN_PRIVATE_KEY zothub.io/c3/${DISTRO}/${folder}-${ARCH}:${tag}-squashfs
+            hack/tools/bin/zli cve local -I c3/${DISTRO}/${folder}-${ARCH}:${tag}
+          done
         env:
-          TAGS: ${{ env.IMAGE_TAG }}
-          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
-          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
-      - name: Sign image with a key (squashfs)
-        run: |
-          cosign sign --key env://COSIGN_PRIVATE_KEY zothub.io/c3/${{ env.DISTRO }}/${{ env.IMAGE }}:${TAGS}
-        env:
-          TAGS: ${{ env.IMAGE_TAG }}-squashfs
           COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
           COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
